apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"europe-west1.svc.cluster.local": ["34.38.191.213"], "europe-west1-failover.svc.cluster.local": ["34.38.191.213"]}
